### ISSUE TITLE
Is the project dropped?

### ISSUE THREAD

**Issue by brianferri** [seanssullivan/extract-pdf-table#1]
While looking around for a way to extract tabular data from PDF using pdfminer I happened to stumble upon this repo.
I looked through the source and just have to say, this is outstanding work!
Is there any chance that this project will ever be ported to some of the newer versions of python or have it's packages updated to support the latest versions of pdfminer.six?

**Comment by seanssullivan** [comment]
Not dropped, just on hold. I haven't had much time to work on it over the last couple years. However, I did a quick update to the requirements to remove the specific versions and the tests all pass for python 3.8 through 3.11. It doesn't currently work on python 3.12 but that appears to be more a problem with tox and pip (as a result of an update to `pkgutil` in 3.12) rather than the code itself.

**Comment by brianferri** [comment]
That's fantastic!! I really appreciate the work you've done here, keep it up! 👍
